=== codjo-sandbox/codjo-sql/codjo-sql-builder/src/main/resources/net/codjo/sql/builder/query-config.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:simpleType name="JoinKeyTypeType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="inner"/>
            <xsd:enumeration value="left"/>
            <xsd:enumeration value="right"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="PartOperatorType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="="/>
            <xsd:enumeration value="!="/>
            <xsd:enumeration value="&lt;&gt;"/>
            <xsd:enumeration value="&lt;"/>
            <xsd:enumeration value="&gt;"/>
            <xsd:enumeration value="&lt;="/>
            <xsd:enumeration value="&gt;="/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="PartType">
        <xsd:attribute name="left" type="xsd:string"/>
        <xsd:attribute name="operator" type="PartOperatorType"/>
        <xsd:attribute name="right" type="xsd:string"/>
    </xsd:complexType>

    <xsd:complexType name="JoinKeyType">
        <xsd:sequence>
            <xsd:element name="part" type="PartType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="left" type="xsd:string"/>
        <xsd:attribute name="type" type="JoinKeyTypeType"/>
        <xsd:attribute name="right" type="xsd:string"/>
    </xsd:complexType>

    <xsd:complexType name="QueryConfigType">
        <xsd:sequence>
            <xsd:element name="join-key" type="JoinKeyType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string"/>
        <xsd:attribute name="root" type="xsd:string"/>
    </xsd:complexType>

    <xsd:complexType name="ConfigListType">
        <xsd:sequence>
            <xsd:element name="query-config" type="QueryConfigType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:element name="config-list" type="ConfigListType"/>
</xsd:schema>

=== codjo-sandbox/codjo-sql/codjo-sql-builder/src/test/resources/net/codjo/sql/builder/XmlQueryConfigListTest.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<config-list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="query-config.xsd">

    <query-config id="config1" root="AP_ROOT">
        <join-key left="AP_ROOT" type="inner" right="AP_A">
            <part left="COL_R1" operator="=" right="COL_A1"/>
        </join-key>
        <join-key left="AP_A" type="left" right="AP_B">
            <part left="COL_A1" operator="=" right="COL_B1"/>
            <part left="COL_A2" operator="&lt;" right="COL_B2"/>
        </join-key>
        <join-key left="AP_C" type="right" right="AP_ROOT">
            <part left="COL_C1" operator="&gt;=" right="COL_R1"/>
        </join-key>
    </query-config>

    <query-config id="config2" root="AP_ROOT_2">
        <join-key left="AP_ROOT_2" type="left" right="AP_T">
            <part left="COL_R1" operator="=" right="COL_A1"/>
        </join-key>
    </query-config>

    <query-config id="config3" root="AP_ROOT_3">
        <!--join-key left="AP_ROOT_2" type="left" right="AP_T">
            <part left="COL_R1" operator="=" right="COL_A1"/>
        </join-key-->
    </query-config>

</config-list>
